version: '3'
services:
    saga-web:
        image: 'kietara/sagaweb:latest'
        pull_policy: always
        ports:
            - '13200:8080'
        environment:
            - spring.datasource.url=jdbc:mysql://192.168.88.254:3306/sagaeco
            # - spring.datasource.password=$SAGADB_PASSWORD