name: DEPLOYMENT

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    environment:
      name: Production
      url: 'https://econline.org'
   
    steps:
    # CHECKOUT SOURCE CODE
    - uses: actions/checkout@v2

    # SETING UP JAVA FOR BUILD
    - uses: actions/setup-java@v1
      with:
        java-version: '11'

    # BUILD ONLY NOT TEST & UPLOAD RESULT
    - name: Build Artifact
      run: mvn clean install -DskipTests

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: '${{ github.workspace }}/target/*.jar'
  
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    
    - name: Load Artifact
      uses: actions/download-artifact@v2
      with:
        name: artifact
        path: '${{ github.workspace }}/target'
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: kietara/sagaweb:latest